### ISSUE TITLE
Which book it is?

### ISSUE THREAD

**Issue by kenorb** [Lucas170/Chapter-1-All-Files#1]
Could you include the information from which book these examples in your repositories are from? It would be very useful.

**Comment by lukas17** [comment]
Hey Kenorb, this EA was built from this template builder: http://sufx.core.t3-ism.net/ExpertAdvisorBuilder/. The site has been shut down though.

**Comment by kenorb** [comment]
[Here is the cached version of that page](http://web.archive.org/web/20160829200307/http://sufx.core.t3-ism.net:80/ExpertAdvisorBuilder/forum/viewtopic.php?p=57825).

I meant, from which book are these chapters.
